config/routes.rb
Apitome::Engine.routes.draw do
  root to: "docs#index"
  get "/simulate/*path", to: "docs#simulate", as: :simulated
  get "/*path", to: "docs#show" unless Apitome.configuration.single_page
end

app/controllers/apitome/docs_controller.rb
require 'open-uri'

class Apitome::DocsController < Object.const_get(Apitome.configuration.parent_controller)
  layout Apitome.configuration.layout

  helper_method *[
    :resources,
    :example,
    :formatted_body,
    :param_headers,
    :param_extras,
    :formatted_readme,
    :set_example,
    :id_for,
    :rendered_markdown
  ]

  def index
  end

  def show
  end

  def simulate
    request = example["requests"][0]
    if request
      request["response_headers"].delete('Content-Length')
      request["response_headers"].each { |k, v| headers[k] = v }
      render body: request["response_body"], status: request["response_status"]
    else
      render body: "No simulation for this endpoint", status: 404
    end
  end

  private

  def file_for(file, readme: false)
    if Apitome.configuration.remote_docs
      file = if readme
        "#{file}"
      else
        "#{Apitome.configuration.doc_path}/#{file}"
      end

      file = "#{Apitome.configuration.remote_url}/#{file}"
    else
      file = Apitome.configuration.root.join(Apitome.configuration.doc_path, file)
      raise Apitome::FileNotFoundError.new("Unable to find #{file}") unless File.exists?(file)
    end

    open(file).read
  end

  def resources
    @resources ||= JSON.parse(file_for("index.json"))["resources"]
  end

  def example
    @example ||= JSON.parse(file_for("#{params[:path]}.json"))
  end

  def set_example(resource)
    @example = JSON.parse(file_for("#{resource}.json"))
  end

  def formatted_readme
    return unless Apitome.configuration.readme
    rendered_markdown(file_for(Apitome.configuration.readme, readme: true))
  end

  def rendered_markdown(string)
    if defined?(GitHub::Markdown)
      GitHub::Markdown.render(string)
    else
      Kramdown::Document.new(string).to_html
    end
  end

  def formatted_body(body, type)
    if type =~ /json/ && body.present?
      JSON.pretty_generate(JSON.parse(body))
    else
      body
    end
  rescue JSON::ParserError
    return body if body == " "
    raise JSON::ParserError
  end

  def param_headers(params)
    titles = %w{Name Description}
    titles += param_extras(params)
    titles
  end

  def param_extras(params)
    params.map do |param|
      param.reject { |k, _v| %w{name description required scope}.include?(k) }.keys
    end.flatten.uniq
  end

  def id_for(str)
    Apitome.configuration.url_formatter.call(str)
  end
end

app/helpers/apitome/docs_helper.rb
module Apitome::DocsHelper
  def format_scope(scope)
    Array(scope).each_with_index.map do |scope, index|
      if index == 0
        scope
      else
        "[#{scope}]"
      end
    end.join
  end

  def resource_link(resource)
    "#{Apitome.configuration.mount_at}/#{resource['examples'].first['link'].gsub(/\.json$/, '')}"
  end

  def example_link(example)
    "#{Apitome.configuration.mount_at}/#{example['link'].gsub(/\.json$/, '')}"
  end

  def link_active?(link)
    current_page?(url_for(link))
  end
end

app/views/apitome/docs/_body.html.erb
<section class="body">
  <h4><%= t(:body, scope: :apitome) %></h4>
  <pre><code class="<%= type %>"><%= formatted_body(body, type) %></code></pre>
</section>

app/views/apitome/docs/_curl.html.erb
<section class="curl">
  <h4><%= t(:curl, scope: :apitome) %></h4>
  <pre><%= request['curl'] %></pre>
</section>

app/views/apitome/docs/_endpoint.html.erb
<section class="endpoint">
  <h3><%= t(:endpoint, scope: :apitome) %></h3>
  <pre><%= "#{method} #{endpoint}" %></pre>
</section>

app/views/apitome/docs/_example.html.erb
<h2><%= example['description'] %></h2>

<%= render partial: 'apitome/docs/explanation',    locals: {explaination: example['explanation']} if example['explanation'] %>
<%= render partial: 'apitome/docs/endpoint',       locals: {method: example['http_method'], endpoint: example['route']} %>
<%= render partial: 'apitome/docs/params',         locals: {params: example['parameters']} if example['parameters'].size > 0 %>

<% example['requests'].each_with_index do |request, index| %>
  <div id="<%= "request-#{index}" %>">
    <h3><%= t(:request, scope: :apitome) %></h3>
    <div class="request">
      <%= render partial: 'apitome/docs/route',    locals: {request: request, index: index} %>
      <%= render partial: 'apitome/docs/headers',  locals: {request: request, index: index, headers: request['request_headers']} %>
      <%= render partial: 'apitome/docs/query',    locals: {request: request, index: index} unless request['request_query_parameters'].empty? %>
      <%= render partial: 'apitome/docs/body',     locals: {request: request, index: index, body: request['request_body'], type: request['request_content_type']} if request['request_body'] %>
      <%= render partial: 'apitome/docs/curl',     locals: {request: request, index: index} if request['curl'] %>
    </div>

    <h3><%= t(:response, scope: :apitome) %></h3>
    <div class="response">
      <%= link_to('Simulated Response', simulated_path(link)) unless link.empty? %>
      <%= render partial: 'apitome/docs/response_fields', locals: {params: example['response_fields']} if example['response_fields'].size > 0 %>
      <%= render partial: 'apitome/docs/status',          locals: {request: request, index: index} %>
      <%= render partial: 'apitome/docs/headers',         locals: {request: request, index: index, headers: request['response_headers']} %>
      <%= render partial: 'apitome/docs/body',            locals: {request: request, index: index, body: request['response_body'], type: request['response_content_type']} if request['response_body'] %>
    </div>
  </div>
<% end %>

app/views/apitome/docs/_explanation.html.erb
<div class="explanation">
  <%= raw rendered_markdown(example['explanation'].strip_heredoc) %>
</div>

app/views/apitome/docs/_header.html.erb
<header class="navbar navbar-fixed-top docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <h1 class="navbar-brand"><a href="<%= Apitome.configuration.mount_at %>"><%= Apitome.configuration.title %></a></h1>
    </div>
  </div>
</header>

app/views/apitome/docs/_navigation.html.erb
<ul class="nav sidenav">
  <% if Apitome.configuration.readme %>
    <li>
      <% if Apitome.configuration.single_page %>
        <a href="#readme"><%= t(:readme, scope: :apitome) %></a>
      <% else %>
        <a href="<%= Apitome.configuration.mount_at %>"><%= t(:readme, scope: :apitome) %></a>
      <% end %>
    </li>
  <% end %>
  <% resources.each do |resource| %>
    <li>
      <% if Apitome.configuration.single_page %>
        <a href="#<%= id_for(resource['name']) %>"><%= resource['name'] %></a>
        <ul class="nav">
          <% resource['examples'].each do |example| %>
            <li><%= link_to example['description'], "##{id_for(example['link'])}" %></li>
          <% end %>
        </ul>
      <% else %>
        <%= link_to resource['name'], resource_link(resource), class: "#{link_active?(resource_link(resource)) ? 'active' : ''}" %>
        <ul class="nav">
          <% resource['examples'].each do |example| %>
            <li class="<%= link_active?(example_link(example)) ? 'active' : '' %>">
              <%= link_to example['description'], example_link(example) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/apitome/docs/_params.html.erb
<section class="params">
  <h3><%= t(:parameters, scope: :apitome) %></h3>
  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <% param_headers(params).each do |title| %>
          <th><%= title %></th>
        <% end %>
      </tr>
      <% params.each do |param| %>
        <tr>
          <td class="name">
            <% if param['scope'] %>
              <%= "#{format_scope(param['scope'])}[#{param['name']}]" %>
            <% else %>
              <%= param['name'] %>
            <% end %>
            <% if param['required'] %>
              <span class="label label-danger required"><%= t(:required, scope: :apitome) %></span>
            <% end %>
          </td>
          <td class="description"><%= param['description'] %></td>
          <% param_extras(params).each do |extra| %>
            <td class="extra"><%= param[extra] %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</section>

app/views/apitome/docs/_query.html.erb
<section class="query-parameters">
  <h4><%= t(:query_parameters, scope: :apitome) %></h4>
  <pre><%= request['request_query_parameters'].map{ |k,v| "#{k}=#{v}" }.join("\n") %></pre>
</section>

app/views/apitome/docs/_resource_explanation.html.erb
<article class="resource_explanation">
  <%= raw rendered_markdown(explanation.strip_heredoc) %>
</article>

app/views/apitome/docs/_response_fields.html.erb
<section class="params">
  <h3><%= t(:response_fields, scope: :apitome) %></h3>
  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <% param_headers(params).each do |title| %>
          <th><%= title %></th>
        <% end %>
      </tr>
      <% params.each do |param| %>
        <tr>
          <td class="name">
            <% if param['scope'] %>
              <%= "#{param['scope']}[#{param['name']}]" %>
            <% else %>
              <%= param['name'] %>
            <% end %>
          </td>
          <td class="description"><%= param['description'] %></td>
          <% param_extras(params).each do |extra| %>
            <td class="extra"><%= param[extra] %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</section>

app/views/apitome/docs/_route.html.erb
<section class="route">
  <h4><%= t(:route, scope: :apitome) %></h4>
  <pre><%= "#{request['request_method']} #{request['request_path']}" %></pre>
</section>

app/views/apitome/docs/index.html.erb
<% if Apitome.configuration.readme %>
  <section class="readme" id="readme">
    <article>
      <%= raw formatted_readme %>
    </article>
  </section>
<% end %>
<% if Apitome.configuration.single_page %>
    <a href="#top" id="scroll-to-top" class="hidden btn btn-primary">Back to Top</a>
<% end %>
<%= render 'all_examples' if Apitome.configuration.single_page %>

app/views/apitome/docs/show.html.erb
<h1 class="resource-name"><%= example['resource'] %></h1>
<%= render partial: 'resource_explanation', locals: { explanation: example['resource_explanation'] } if example['resource_explanation'] %>
<%= render partial: 'example', locals: { example: example, link: example['link'].to_s.gsub('.json', '') } %>

app/views/layouts/apitome/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Apitome.configuration.title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    Apitome.configuration.code_theme_url, media: 'all' %>
  <%= stylesheet_link_tag    Apitome.configuration.css_override || 'apitome/application', media: 'all' %>
  <%= javascript_include_tag Apitome.configuration.js_override || 'apitome/application' %>
</head>
<body class="<%= Apitome.configuration.single_page ? 'single-page' : '' %>">

<div class="container">
  <%= render 'header' %>
  <div class="container docs-container">
    <div class="row">
      <div class="col-md-4">
        <div id="sidebar" class="sidebar hidden-print" role="complementary">
          <%= render 'navigation' %>
        </div>
      </div>
      <div class="col-md-8" role="main">
        <div class="docs-section">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>